%% visualize_patches.m
%
% Standalone visualisation script for the patch dataset generated by
% gen_dataset_from_dem.m.  Completely independent of validate_dataset.m.
%
% For each requested index the script opens one figure with up to 9 subplots
% (one per available data type) using imagesc.
%
% Index definition
% ────────────────
%   All .mat files in the reference sub-folder (wrappedphase_withoutnoise)
%   are sorted by the numeric suffix embedded in their filename
%   (i.e. the global_id, e.g. "00042" in
%   "srtm_tile_patch_00042_wrapped_phase.mat").
%   idx = 1  →  the file whose numeric suffix is the smallest,
%   idx = 2  →  the next, …  (1-based position in sorted order).
%
% Usage
% ─────
%   1. Adjust the USER CONFIGURATION section below.
%   2. Run the script inside MATLAB.
%
% -------------------------------------------------------------------------
clc; close all;

%% ══════════════════════════════════════════════════════════════════════════
%  USER CONFIGURATION
%  ══════════════════════════════════════════════════════════════════════════

% Root of the patches output (must match gen_dataset_from_dem.m)
script_dir    = fileparts(mfilename('fullpath'));  % dem2phase/scripts/
dem2phase_dir = fileparts(script_dir);            % dem2phase/
repo_root     = fileparts(dem2phase_dir);         % repo root
output_root   = fullfile(repo_root, 'data', 'training_dataset_v13');

% Indices to visualise (1-based positions in the filename-suffix-sorted list).
% Examples:
%   idx_list = [1, 2, 3];      % first three patches
%   idx_list = 1:10;           % patches 1 to 10
%   idx_list = [5, 23, 100];   % arbitrary selection
idx_list = 13;

%% ══════════════════════════════════════════════════════════════════════════
%  END USER CONFIGURATION
%  ══════════════════════════════════════════════════════════════════════════

% Sub-folder map (mirrors gen_dataset_from_dem.m / validate_dataset.m)
SUBDIRS = struct( ...
    'wrapped_phase',                'wrappedphase_withoutnoise', ...
    'wrapped_phase_real',           'wrappedphase_withoutnoise_real', ...
    'wrapped_phase_imag',           'wrappedphase_withoutnoise_imag', ...
    'wrapped_phase_withnoise',      'wrappedphase_withnoise', ...
    'wrapped_phase_withnoise_real', 'wrappedphase_withnoise_real', ...
    'wrapped_phase_withnoise_imag', 'wrappedphase_withnoise_imag', ...
    'unwrapped_phase',              'unwrapped_phase', ...
    'wrap_count',                   'wrapped_number', ...
    'coherence_estimated',          'coherence_estimated');

% Fixed display order and subplot titles
VIS_ORDER = { ...
    'wrapped_phase',                'Wrapped phase (clean)'; ...
    'wrapped_phase_withnoise',      'Wrapped phase (noisy)'; ...
    'unwrapped_phase',              'Unwrapped phase'; ...
    'wrapped_phase_real',           'Real part – clean'; ...
    'wrapped_phase_imag',           'Imag part – clean'; ...
    'wrapped_phase_withnoise_real', 'Real part – noisy'; ...
    'wrapped_phase_withnoise_imag', 'Imag part – noisy'; ...
    'wrap_count',                   'Wrap count'; ...
    'coherence_estimated',          'Coherence (estimated)'};

type_names = fieldnames(SUBDIRS);

%% ── Validate output root ─────────────────────────────────────────────────
if ~exist(output_root, 'dir')
    error('visualize_patches:missingRoot', ...
        'Output root not found:\n  %s\nRun gen_dataset_from_dem.m first.', ...
        output_root);
end

%% ── Build sorted file list from the reference sub-folder ─────────────────
ref_dir = fullfile(output_root, SUBDIRS.wrapped_phase);
if ~exist(ref_dir, 'dir')
    error('visualize_patches:missingRefDir', ...
        'Reference sub-folder not found:\n  %s', ref_dir);
end

ref_mats = dir(fullfile(ref_dir, '*.mat'));
if isempty(ref_mats)
    error('visualize_patches:noFiles', ...
        'No .mat files found in:\n  %s', ref_dir);
end

% Extract numeric suffix (global_id) from each filename.
% Expected pattern: anything + "_patch_" + digits + "_wrapped_phase.mat"
% Falls back to the first run of digits found in the stem when the
% canonical pattern is absent.
n_files  = numel(ref_mats);
num_ids  = zeros(n_files, 1);
for fi = 1:n_files
    stem = ref_mats(fi).name;
    tok  = regexp(stem, '_patch_(\d+)_', 'tokens', 'once');
    if ~isempty(tok)
        num_ids(fi) = str2double(tok{1});
    else
        % Fallback: rightmost contiguous digit block immediately before the
        % first underscore or dot that follows all digits in the stem.
        % This is intentionally conservative: if the canonical
        % "_patch_NNNNN_" pattern is absent the file sorts to position 0
        % (front of the list) rather than misidentifying digits from an
        % unrelated part of the name.
        tok2 = regexp(stem, '_(\d+)[_.]', 'tokens');
        if ~isempty(tok2)
            num_ids(fi) = str2double(tok2{end}{1});
        end
        % num_ids(fi) stays 0 when no digit block is found, which is
        % acceptable: the file will appear at the start of the sorted list.
    end
end

% Sort files by numeric suffix (ascending)
[~, sort_order] = sort(num_ids);
ref_mats_sorted = ref_mats(sort_order);
n_total = numel(ref_mats_sorted);

fprintf('visualize_patches: %d patches available in sorted order.\n', n_total);

%% ── Visualise requested indices ──────────────────────────────────────────
idx_list = idx_list(:)';  % ensure row vector for uniform iteration
for idx = idx_list
    if idx < 1 || idx > n_total
        fprintf('[SKIP] idx=%d is out of range [1, %d].\n', idx, n_total);
        continue
    end

    mat_name   = ref_mats_sorted(idx).name;
    patch_stem = regexprep(mat_name, '_wrapped_phase\.mat$', '');

    % ── Load all available types ──────────────────────────────────────────
    d = struct();
    for ti = 1:numel(type_names)
        tname = type_names{ti};
        fpath = fullfile(output_root, SUBDIRS.(tname), ...
            sprintf('%s_%s.mat', patch_stem, tname));
        if exist(fpath, 'file')
            s = load(fpath, 'data');
            d.(tname) = s.data;
        end
    end

    % ── Build subplot layout from available types ─────────────────────────
    mask      = cellfun(@(t) isfield(d, t), VIS_ORDER(:,1));
    vis_avail = VIS_ORDER(mask, :);
    n_vis     = size(vis_avail, 1);

    if n_vis == 0
        fprintf('[SKIP] idx=%d (%s): no data files found.\n', idx, patch_stem);
        continue
    end

    n_cols = min(n_vis, 3);
    n_rows = ceil(n_vis / n_cols);

    fig = figure('Name', sprintf('idx=%d  |  %s', idx, patch_stem), ...
                 'NumberTitle', 'off', ...
                 'Units', 'normalized', ...
                 'Position', [0.05, 0.05, 0.9, min(0.9, 0.30*n_rows)]);

    for vi = 1:n_vis
        subplot(n_rows, n_cols, vi);
        imagesc(d.(vis_avail{vi,1}));
        axis image off;
        colorbar;
        title(vis_avail{vi,2}, 'Interpreter', 'none', 'FontSize', 8);
    end

    sgtitle(sprintf('idx = %d  |  %s', idx, strrep(patch_stem, '_', '\_')), ...
        'FontSize', 9, 'FontWeight', 'bold');
    drawnow;

    fprintf('[OK]   idx=%d  ->  %s  (%d panel(s))\n', idx, patch_stem, n_vis);
end

fprintf('Done.\n');
