function tests = test_real_dem_smoke
%TEST_REAL_DEM_SMOKE Exercise the configured pipeline on the bundled GeoTIFF.
    tests = functiontests(localfunctions);
end

function testBundledDemProducesConfiguredBaselineStack(testCase)
    test_dir = fileparts(mfilename('fullpath'));
    project_root = fileparts(test_dir);
    cfg = load_sim_config(fullfile(project_root, 'configs', ...
        'uav_p_500m_monostatic.json'));
    tif_files = dir(fullfile(project_root, '*_DSM*.tif'));
    if isempty(tif_files)
        tif_files = dir(fullfile(project_root, '*_dem*.tif'));
    end
    testCase.assumeNotEmpty(tif_files, ...
        'No bundled DEM/DSM GeoTIFF is available for the smoke test.');

    dem = double(imread(fullfile(tif_files(1).folder, tif_files(1).name)));
    patch_size = min([96, size(dem, 1), size(dem, 2)]);
    patch = dem(1:patch_size, 1:patch_size);
    patch = patch - min(patch(:));

    baselines = double(cfg.interferometry.baseline_perp_m(:)');
    [coh_maps, terrain] = gen_coherence_map_multibaseline_terrainaware( ...
        patch, baselines, ...
        'pixel_spacing_m', double(cfg.dataset.source_dem_pixel_spacing_m), ...
        'incidence_angle_deg', double(cfg.geometry.incidence_angle_deg), ...
        'look_azimuth_deg', double(cfg.geometry.look_azimuth_deg), ...
        'min_coh', double(cfg.coherence.min), ...
        'max_coh', double(cfg.coherence.max), ...
        'baseline_decay_model', char(cfg.coherence.baseline_decay_model), ...
        'critical_baseline_m', double(cfg.physics.critical_baseline_m), ...
        'decay_alpha', double(cfg.coherence.decay_alpha), ...
        'terrain_normalization_model', ...
            char(cfg.coherence.terrain_normalization_model), ...
        'slope_scale_deg', double(cfg.coherence.slope_scale_deg), ...
        'roughness_scale_m', double(cfg.coherence.roughness_scale_m), ...
        'curvature_scale_per_m', double(cfg.coherence.curvature_scale_per_m), ...
        'seed', 31);

    landcover_path = fullfile(project_root, ...
        char(cfg.dataset.landcover.aligned_file));
    landcover = load(landcover_path, 'landcover_codes');
    patch_landcover = landcover.landcover_codes(1:patch_size, 1:patch_size);
    [coh_maps, landcover_info] = apply_landcover_coherence( ...
        coh_maps, patch_landcover, cfg.dataset.landcover, ...
        double(cfg.coherence.min));

    ratios = double(cfg.physics.dem2phase_ratios_rad_per_m(:)');
    clean_unwrapped = arrayfun(@(k) patch*ratios(k), ...
        1:numel(baselines), 'UniformOutput', false);
    clean = cellfun(@(phase) angle(exp(1i*phase)), clean_unwrapped, ...
        'UniformOutput', false);
    node_snr_db = ones(1, double(cfg.interferometry.num_uavs))*22;
    [noisy, node_slc, effective_coherence] = ...
        simulate_distributed_slc_star(clean, coh_maps, ...
            cfg.interferometry.edge_index, ...
            double(cfg.interferometry.num_uavs), ...
            'node_snr_db', node_snr_db, 'seed', 101);

    mask = logical([1, 1, 0, 1]);
    metadata.patch_name = 'real_dem_smoke';
    group = build_patch_group(clean, noisy, clean_unwrapped, coh_maps, ...
        effective_coherence, mask, cfg, terrain, metadata);
    group.node_slc = single(node_slc);
    group.landcover_codes = patch_landcover;
    group.landcover_factor = single(landcover_info.factor_map);
    temp_file = [tempname, '.mat'];
    cleanup = onCleanup(@() delete_if_present(temp_file));
    save_patch_group(temp_file, group);
    loaded = load(temp_file);

    verifyNumElements(testCase, coh_maps, numel(baselines));
    verifyNumElements(testCase, noisy, numel(baselines));
    verifySize(testCase, terrain.slope_deg, size(patch));
    verifySize(testCase, loaded.wrappedphase_withnoise, ...
        [numel(baselines), patch_size, patch_size]);
    verifyEqual(testCase, loaded.valid_edge_mask, uint8(mask));
    verifySize(testCase, loaded.node_slc, ...
        [double(cfg.interferometry.num_uavs), patch_size, patch_size]);
    verifySize(testCase, loaded.landcover_codes, [patch_size, patch_size]);
    verifyEqual(testCase, squeeze(loaded.wrappedphase_withnoise(3,:,:)), ...
        zeros(patch_size, patch_size, 'single'));
    for k = 1:numel(baselines)
        verifySize(testCase, coh_maps{k}, size(patch));
        verifyGreaterThanOrEqual(testCase, min(coh_maps{k}(:)), 0);
        verifyLessThanOrEqual(testCase, max(coh_maps{k}(:)), 1);
        verifyGreaterThanOrEqual(testCase, min(noisy{k}(:)), -pi);
        verifyLessThanOrEqual(testCase, max(noisy{k}(:)), pi);
    end
    clear cleanup
end

function delete_if_present(filename)
    if exist(filename, 'file')
        delete(filename);
    end
end
