function cfg = validate_sim_config(cfg)
%VALIDATE_SIM_CONFIG Validate and derive multi-UAV InSAR physics fields.

    required_top = {'dataset', 'radar', 'geometry', 'coherence', 'noise', 'phase4_errors', ...
        'phase4_failures', ...
        'interferometry'};
    require_fields(cfg, required_top, 'config');
    require_fields(cfg.dataset, ...
        {'dem_directory', 'output_directory', 'source_dem_pixel_spacing_m', ...
         'split_manifest', 'require_split_assignment', 'generation', ...
         'landcover', 'storage', 'terrain_sampling'}, 'dataset');
    assert(strlength(string(cfg.dataset.split_manifest)) > 0, ...
        'dem2phase:MissingSplitManifest', ...
        'dataset.split_manifest must name a CSV manifest.');
    require_fields(cfg.radar, {'center_frequency_hz', 'bandwidth_hz'}, 'radar');
    require_fields(cfg.geometry, ...
        {'altitude_m', 'incidence_angle_deg', 'slant_range_m'}, 'geometry');
    require_fields(cfg.interferometry, ...
        {'measurement_mode', 'phase_path_multiplicity', 'num_uavs', ...
         'edge_mode', 'reference_uav', 'baseline_perp_m'}, 'interferometry');

    c0 = 299792458.0;
    frequency_hz = double(cfg.radar.center_frequency_hz);
    bandwidth_hz = double(cfg.radar.bandwidth_hz);
    altitude_m = double(cfg.geometry.altitude_m);
    theta_deg = double(cfg.geometry.incidence_angle_deg);
    slant_range_m = double(cfg.geometry.slant_range_m);
    baselines_m = double(cfg.interferometry.baseline_perp_m(:)');
    num_uavs = double(cfg.interferometry.num_uavs);
    path_multiplicity = double(cfg.interferometry.phase_path_multiplicity);

    assert(isfinite(frequency_hz) && frequency_hz > 0, ...
        'dem2phase:InvalidFrequency', 'center_frequency_hz must be positive.');
    assert(isfinite(bandwidth_hz) && bandwidth_hz > 0 && bandwidth_hz < frequency_hz, ...
        'dem2phase:InvalidBandwidth', ...
        'bandwidth_hz must be positive and smaller than center_frequency_hz.');
    assert(isfinite(altitude_m) && altitude_m > 0, ...
        'dem2phase:InvalidAltitude', 'altitude_m must be positive.');
    assert(isfinite(theta_deg) && theta_deg > 0 && theta_deg < 90, ...
        'dem2phase:InvalidIncidenceAngle', ...
        'incidence_angle_deg must lie strictly between 0 and 90 degrees.');
    assert(isfinite(slant_range_m) && slant_range_m >= altitude_m, ...
        'dem2phase:InvalidSlantRange', ...
        'slant_range_m must be finite and no smaller than altitude_m.');
    assert(~isempty(baselines_m) && all(isfinite(baselines_m)) && all(baselines_m > 0), ...
        'dem2phase:InvalidBaselines', ...
        'baseline_perp_m must contain positive finite values.');
    assert(num_uavs == fix(num_uavs) && num_uavs >= 2, ...
        'dem2phase:InvalidUavCount', 'num_uavs must be an integer >= 2.');

    if isfield(cfg, 'dataset') && isfield(cfg.dataset, 'source_dem_pixel_spacing_m')
        spacing_m = double(cfg.dataset.source_dem_pixel_spacing_m);
        assert(isfinite(spacing_m) && spacing_m > 0, ...
            'dem2phase:InvalidDemPixelSpacing', ...
            'dataset.source_dem_pixel_spacing_m must be positive.');
    end
    generation = cfg.dataset.generation;
    require_fields(generation, {'patches_per_dem', 'patch_size', ...
        'n_precomp_scales', 'interp_scale_range', 'rng_seed', ...
        'max_wrap_count', 'void_fraction_threshold'}, 'dataset.generation');
    positive_integers = [double(generation.patches_per_dem), ...
        double(generation.patch_size), double(generation.n_precomp_scales)];
    assert(all(positive_integers >= 1) && all(positive_integers == fix(positive_integers)), ...
        'dem2phase:InvalidGenerationCounts', ...
        'Generation patch and scale counts must be positive integers.');
    scale_range = double(generation.interp_scale_range(:)');
    assert(numel(scale_range) == 2 && scale_range(1) > 0 && ...
        scale_range(2) >= scale_range(1), 'dem2phase:InvalidScaleRange', ...
        'dataset.generation.interp_scale_range must be [minimum, maximum].');
    seed = double(generation.rng_seed);
    assert(isscalar(seed) && isfinite(seed) && seed >= 0 && seed == fix(seed), ...
        'dem2phase:InvalidRngSeed', ...
        'dataset.generation.rng_seed must be a nonnegative integer.');
    sampling = cfg.dataset.terrain_sampling;
    require_fields(sampling, {'mode', 'max_attempts_factor'}, ...
        'dataset.terrain_sampling');
    sampling_mode = char(sampling.mode);
    assert(ismember(sampling_mode, {'uniform', 'weighted'}), ...
        'dem2phase:UnsupportedTerrainSamplingMode', ...
        'dataset.terrain_sampling.mode must be uniform or weighted.');
    max_attempts_factor = double(sampling.max_attempts_factor);
    assert(isfinite(max_attempts_factor) && max_attempts_factor >= 1, ...
        'dem2phase:InvalidMaxAttemptsFactor', ...
        'dataset.terrain_sampling.max_attempts_factor must be >= 1.');
    if strcmp(sampling_mode, 'weighted')
        require_fields(sampling, {'acceptance_probability'}, ...
            'dataset.terrain_sampling');
        probability_names = {'flat', 'rolling', 'steep', 'geometry_hazard'};
        require_fields(sampling.acceptance_probability, probability_names, ...
            'dataset.terrain_sampling.acceptance_probability');
        for probability_idx = 1:numel(probability_names)
            probability = double(sampling.acceptance_probability. ...
                (probability_names{probability_idx}));
            assert(isfinite(probability) && probability > 0 && probability <= 1, ...
                'dem2phase:InvalidTerrainAcceptanceProbability', ...
                'Terrain acceptance probabilities must lie in (0, 1].');
        end
    end
    storage = cfg.dataset.storage;
    require_fields(storage, {'mode', 'write_legacy_per_edge', 'numeric_type'}, ...
        'dataset.storage');
    assert(strcmp(char(storage.mode), 'grouped_mat'), ...
        'dem2phase:UnsupportedStorageMode', ...
        'dataset.storage.mode must be grouped_mat.');
    assert(ismember(char(storage.numeric_type), {'single', 'double'}), ...
        'dem2phase:UnsupportedNumericType', ...
        'dataset.storage.numeric_type must be single or double.');
    landcover = cfg.dataset.landcover;
    require_fields(landcover, {'enabled', 'aligned_file', 'aligned_directory', ...
        'aligned_suffix', 'missing_policy', 'source', 'profile', ...
        'unknown_factor', 'class_codes', 'coherence_factors', 'sampling'}, ...
        'dataset.landcover');
    assert(ismember(char(landcover.missing_policy), {'neutral', 'error'}), ...
        'dem2phase:InvalidLandcoverMissingPolicy', ...
        'dataset.landcover.missing_policy must be neutral or error.');
    class_codes = double(landcover.class_codes(:)');
    class_factors = double(landcover.coherence_factors(:)');
    assert(numel(class_codes) == numel(class_factors) && ...
        numel(unique(class_codes)) == numel(class_codes), ...
        'dem2phase:InvalidLandcoverMapping', ...
        'Land-cover codes must be unique and match coherence_factors in length.');
    assert(all(class_factors >= 0) && all(class_factors <= 1) && ...
        landcover.unknown_factor >= 0 && landcover.unknown_factor <= 1, ...
        'dem2phase:InvalidLandcoverFactor', ...
        'Land-cover coherence factors must lie within [0,1].');
    landcover_sampling = landcover.sampling;
    require_fields(landcover_sampling, {'enabled', 'priority_codes', ...
        'minimum_fraction', 'acceptance_multiplier'}, ...
        'dataset.landcover.sampling');
    priority_codes = double(landcover_sampling.priority_codes(:)');
    minimum_fraction = double(landcover_sampling.minimum_fraction(:)');
    acceptance_multiplier = double(landcover_sampling.acceptance_multiplier(:)');
    assert(numel(priority_codes) == numel(minimum_fraction) && ...
        numel(priority_codes) == numel(acceptance_multiplier), ...
        'dem2phase:InvalidLandcoverSampling', ...
        'Land-cover sampling arrays must have equal lengths.');
    assert(all(ismember(priority_codes, class_codes)) && ...
        all(minimum_fraction >= 0 & minimum_fraction <= 1) && ...
        all(acceptance_multiplier >= 1), ...
        'dem2phase:InvalidLandcoverSamplingValues', ...
        'Land-cover priorities, fractions, or multipliers are invalid.');
    if isfield(cfg.geometry, 'look_azimuth_deg')
        look_azimuth_deg = double(cfg.geometry.look_azimuth_deg);
        assert(isfinite(look_azimuth_deg), ...
            'dem2phase:InvalidLookAzimuth', ...
            'geometry.look_azimuth_deg must be finite.');
    end
    if isfield(cfg, 'coherence')
        require_fields(cfg.coherence, ...
            {'model', 'baseline_decay_model', 'terrain_normalization_model', ...
             'min', 'max', 'decay_alpha', 'slope_scale_deg', ...
             'roughness_scale_m', 'curvature_scale_per_m'}, ...
            'coherence');
        assert(strcmp(char(cfg.coherence.model), 'terrain_aware'), ...
            'dem2phase:UnsupportedCoherenceModel', ...
            'The configured coherence.model must be terrain_aware.');
        coh_min = double(cfg.coherence.min);
        coh_max = double(cfg.coherence.max);
        assert(coh_min > 0 && coh_max < 1 && coh_min < coh_max, ...
            'dem2phase:InvalidCoherenceRange', ...
            'coherence.min and coherence.max must satisfy 0 < min < max < 1.');
        assert(ismember(char(cfg.coherence.baseline_decay_model), ...
            {'critical_baseline', 'exponential'}), ...
            'dem2phase:UnsupportedBaselineDecayModel', ...
            'coherence.baseline_decay_model must be critical_baseline or exponential.');
        assert(ismember(char(cfg.coherence.terrain_normalization_model), ...
            {'absolute_scales', 'patch_percentile'}), ...
            'dem2phase:UnsupportedTerrainNormalizationModel', ...
            ['coherence.terrain_normalization_model must be absolute_scales ' ...
             'or patch_percentile.']);
        terrain_scales = [double(cfg.coherence.slope_scale_deg), ...
            double(cfg.coherence.roughness_scale_m), ...
            double(cfg.coherence.curvature_scale_per_m)];
        assert(all(isfinite(terrain_scales)) && all(terrain_scales > 0), ...
            'dem2phase:InvalidTerrainScales', ...
            'All configured absolute terrain scales must be positive.');
    end
    require_fields(cfg.noise, ...
        {'model', 'node_snr_db_range', 'multilook_window', 'save_node_slc'}, ...
        'noise');
    noise_model = char(cfg.noise.model);
    assert(ismember(noise_model, {'complex_slc_nodes', 'legacy_phase_pdf'}), ...
        'dem2phase:UnsupportedNoiseModel', ...
        'noise.model must be complex_slc_nodes or legacy_phase_pdf.');
    snr_range = double(cfg.noise.node_snr_db_range(:)');
    assert(numel(snr_range) == 2 && all(isfinite(snr_range)) && ...
        snr_range(2) >= snr_range(1), ...
        'dem2phase:InvalidNodeSnrRange', ...
        'noise.node_snr_db_range must be [minimum, maximum] in dB.');
    multilook_window = double(cfg.noise.multilook_window);
    assert(isfinite(multilook_window) && multilook_window >= 1 && ...
        multilook_window == fix(multilook_window) && mod(multilook_window, 2) == 1, ...
        'dem2phase:InvalidMultilookWindow', ...
        'noise.multilook_window must be a positive odd integer.');

    errors = cfg.phase4_errors;
    require_fields(errors, {'enabled', 'profile', 'synchronization', ...
        'trajectory', 'attitude', 'coregistration'}, 'phase4_errors');
    require_fields(errors.synchronization, {'phase_bias_std_rad', ...
        'linear_drift_std_rad', 'random_walk_std_rad_per_row', ...
        'jump_probability_per_node', 'jump_std_rad'}, ...
        'phase4_errors.synchronization');
    require_fields(errors.trajectory, {'los_bias_std_m', 'los_drift_std_m', ...
        'vibration_std_m', 'vibration_cycles_range'}, ...
        'phase4_errors.trajectory');
    require_fields(errors.attitude, {'roll_std_deg', 'pitch_std_deg'}, ...
        'phase4_errors.attitude');
    require_fields(errors.coregistration, {'range_shift_std_px', ...
        'azimuth_shift_std_px', 'linear_drift_std_px'}, ...
        'phase4_errors.coregistration');
    error_scales = [double(errors.synchronization.phase_bias_std_rad), ...
        double(errors.synchronization.linear_drift_std_rad), ...
        double(errors.synchronization.random_walk_std_rad_per_row), ...
        double(errors.synchronization.jump_std_rad), ...
        double(errors.trajectory.los_bias_std_m), ...
        double(errors.trajectory.los_drift_std_m), ...
        double(errors.trajectory.vibration_std_m), ...
        double(errors.attitude.roll_std_deg), double(errors.attitude.pitch_std_deg), ...
        double(errors.coregistration.range_shift_std_px), ...
        double(errors.coregistration.azimuth_shift_std_px), ...
        double(errors.coregistration.linear_drift_std_px)];
    assert(all(isfinite(error_scales)) && all(error_scales >= 0), ...
        'dem2phase:InvalidPhase4ErrorScale', ...
        'All Phase-4 error scales must be finite and nonnegative.');
    jump_probability = double(errors.synchronization.jump_probability_per_node);
    assert(jump_probability >= 0 && jump_probability <= 1, ...
        'dem2phase:InvalidJumpProbability', ...
        'Synchronization jump probability must lie in [0,1].');
    vibration_cycles = double(errors.trajectory.vibration_cycles_range(:)');
    assert(numel(vibration_cycles) == 2 && vibration_cycles(1) >= 0 && ...
        vibration_cycles(2) >= vibration_cycles(1), ...
        'dem2phase:InvalidVibrationCycles', ...
        'vibration_cycles_range must be [minimum, maximum].');
    failures = cfg.phase4_failures;
    require_fields(failures, {'enabled', 'profile', ...
        'force_secondary_uav_dropout', 'always_include_shortest', ...
        'always_include_longest', 'low_coherence_threshold', ...
        'low_coherence_min_fraction', 'sync_jump_min_abs_rad'}, ...
        'phase4_failures');
    low_threshold = double(failures.low_coherence_threshold);
    low_fraction = double(failures.low_coherence_min_fraction);
    assert(low_threshold > 0 && low_threshold < 1 && ...
        low_fraction >= 0 && low_fraction <= 1 && ...
        failures.sync_jump_min_abs_rad >= 0, ...
        'dem2phase:InvalidPhase4FailureThreshold', ...
        'Phase-4 failure thresholds are invalid.');
    if logical(failures.enabled)
        assert(logical(errors.enabled) && strcmp(noise_model, 'complex_slc_nodes'), ...
            'dem2phase:CompoundFailureRequiresNodeSlc', ...
            'Compound failures require enabled Phase-4 errors and complex_slc_nodes.');
    end

    measurement_mode = char(cfg.interferometry.measurement_mode);
    valid_modes = {'monostatic_pair', 'single_tx_multireceiver'};
    assert(ismember(measurement_mode, valid_modes), ...
        'dem2phase:UnsupportedMeasurementMode', ...
        'measurement_mode must be monostatic_pair or single_tx_multireceiver.');
    expected_multiplicity = 2 - strcmp(measurement_mode, 'single_tx_multireceiver');
    assert(path_multiplicity == expected_multiplicity, ...
        'dem2phase:PathMultiplicityMismatch', ...
        'phase_path_multiplicity must be %d for measurement_mode=%s.', ...
        expected_multiplicity, measurement_mode);

    graph = build_interferometric_graph(num_uavs, ...
        char(cfg.interferometry.edge_mode), ...
        double(cfg.interferometry.reference_uav));
    assert(numel(baselines_m) == size(graph.edge_index, 2), ...
        'dem2phase:BaselineEdgeCountMismatch', ...
        ['baseline_perp_m contains %d values, but edge_mode=%s with %d UAVs ' ...
         'requires %d interferometric edges.'], ...
        numel(baselines_m), graph.edge_mode, num_uavs, size(graph.edge_index, 2));
    if strcmp(noise_model, 'complex_slc_nodes')
        assert(strcmp(graph.edge_mode, 'star'), ...
            'dem2phase:ComplexSlcRequiresStarGraph', ...
            ['The first complex node-SLC implementation requires a star graph. ' ...
             'Use legacy_phase_pdf for chain/complete profiles.']);
    end

    if isfield(cfg.interferometry, 'edge_sampling')
        edge_sampling = cfg.interferometry.edge_sampling;
        require_fields(edge_sampling, ...
            {'enabled', 'min_active_edges', 'max_active_edges', ...
             'always_include_shortest'}, 'interferometry.edge_sampling');
        min_edges = double(edge_sampling.min_active_edges);
        max_edges = double(edge_sampling.max_active_edges);
        assert(min_edges == fix(min_edges) && max_edges == fix(max_edges) && ...
            min_edges >= 1 && min_edges <= max_edges && max_edges <= numel(baselines_m), ...
            'dem2phase:InvalidActiveEdgeRange', ...
            'Active-edge range must contain integers within [1, num_edges].');
    end

    if isfield(cfg.interferometry, 'allowed_baseline_perp_m')
        allowed = double(cfg.interferometry.allowed_baseline_perp_m(:)');
        assert(numel(allowed) == 2 && allowed(1) > 0 && allowed(2) >= allowed(1), ...
            'dem2phase:InvalidAllowedBaselineRange', ...
            'allowed_baseline_perp_m must be [minimum, maximum].');
        assert(all(baselines_m >= allowed(1)) && all(baselines_m <= allowed(2)), ...
            'dem2phase:BaselineOutOfRange', ...
            'All baselines must lie within allowed_baseline_perp_m.');
    end

    wavelength_m = c0 / frequency_hz;
    range_resolution_m = c0 / (2*bandwidth_hz);
    critical_baseline_m = wavelength_m * slant_range_m * tand(theta_deg) / ...
        (2*range_resolution_m);
    ratios = path_multiplicity * 2*pi / wavelength_m .* baselines_m ./ ...
        (slant_range_m * sind(theta_deg));
    ambiguity_heights_m = 2*pi ./ ratios;

    if isfield(cfg.interferometry, 'target_ambiguity_height_m')
        target = double(cfg.interferometry.target_ambiguity_height_m(:)');
        assert(numel(target) == numel(ambiguity_heights_m), ...
            'dem2phase:TargetAmbiguityHeightCountMismatch', ...
            'target_ambiguity_height_m must match baseline_perp_m in length.');
        relative_error = abs(target - ambiguity_heights_m) ./ max(target, eps);
        assert(all(relative_error <= 0.01), ...
            'dem2phase:TargetAmbiguityHeightMismatch', ...
            ['Configured target ambiguity heights differ from the derived values ' ...
             'by more than 1%%. Derived values: %s m.'], ...
            mat2str(ambiguity_heights_m, 6));
    end

    cfg.physics.speed_of_light_mps = c0;
    cfg.physics.wavelength_m = wavelength_m;
    cfg.physics.range_resolution_m = range_resolution_m;
    cfg.physics.critical_baseline_m = critical_baseline_m;
    cfg.physics.dem2phase_ratios_rad_per_m = ratios;
    cfg.physics.ambiguity_heights_m = ambiguity_heights_m;
    cfg.interferometry.baseline_perp_m = baselines_m;
    cfg.interferometry.num_edges = numel(baselines_m);
    cfg.interferometry.edge_index = graph.edge_index;
end

function require_fields(value, names, context)
    for idx = 1:numel(names)
        if ~isfield(value, names{idx})
            error('dem2phase:MissingConfigField', ...
                'Missing required field %s.%s.', context, names{idx});
        end
    end
end
