function summary = analyze_phase4_sweep()
%ANALYZE_PHASE4_SWEEP Verify pairing and summarize Phase-4 stress metrics.
    script_dir = fileparts(mfilename('fullpath'));
    project_root = fileparts(script_dir);
    sweep_root = fullfile(project_root, 'data', 'phase4_sweep');
    manifest = jsondecode(fileread(fullfile(project_root, 'configs', ...
        'phase4_sweep_matrix.json')));
    scenarios = cellstr(manifest.scenarios);
    levels = fieldnames(manifest.levels);
    rows = cell(numel(scenarios)*numel(levels), 10);
    row_idx = 0;
    reference = cell(1, manifest.patches_per_dem);

    for scenario_idx = 1:numel(scenarios)
        scenario = scenarios{scenario_idx};
        for level_idx = 1:numel(levels)
            level = levels{level_idx};
            folder = fullfile(sweep_root, sprintf('%s_%s', scenario, level));
            files = dir(fullfile(folder, 'patch_groups', '*.mat'));
            assert(numel(files) == manifest.patches_per_dem, ...
                'dem2phase:IncompletePhase4Sweep', ...
                'Expected %d patches in %s.', manifest.patches_per_dem, folder);
            sync_values = [];
            los_values = [];
            shift_values = [];
            phase_values = [];
            valid_count = 0;
            active_count = 0;
            paired = true;
            for patch_idx = 1:numel(files)
                data = load(fullfile(files(patch_idx).folder, files(patch_idx).name), ...
                    'wrappedphase_withoutnoise', 'wrappedphase_node_noise_only', ...
                    'wrappedphase_withnoise', 'valid_edge_mask', ...
                    'coregistration_valid_mask', 'phase4_errors');
                if scenario_idx == 1 && level_idx == 1
                    reference{patch_idx}.clean = data.wrappedphase_withoutnoise;
                    reference{patch_idx}.node_noise = data.wrappedphase_node_noise_only;
                    reference{patch_idx}.edge_mask = data.valid_edge_mask;
                else
                    paired = paired && ...
                        isequal(reference{patch_idx}.clean, data.wrappedphase_withoutnoise) && ...
                        isequal(reference{patch_idx}.node_noise, ...
                            data.wrappedphase_node_noise_only) && ...
                        isequal(reference{patch_idx}.edge_mask, data.valid_edge_mask);
                end
                active = repmat(reshape(logical(data.valid_edge_mask), [], 1, 1), ...
                    1, size(data.wrappedphase_withnoise,2), ...
                    size(data.wrappedphase_withnoise,3));
                valid = active & logical(data.coregistration_valid_mask);
                difference = angle(exp(1i*(double(data.wrappedphase_withnoise) - ...
                    double(data.wrappedphase_node_noise_only))));
                phase_values = [phase_values; difference(valid)]; %#ok<AGROW>
                sync_values = [sync_values; ...
                    double(data.phase4_errors.sync_phase_error_rad(:))]; %#ok<AGROW>
                los_values = [los_values; ...
                    double(data.phase4_errors.los_range_error_m(:))]; %#ok<AGROW>
                shift_values = [shift_values; ...
                    double(data.phase4_errors.range_displacement_px(:)); ...
                    double(data.phase4_errors.azimuth_displacement_px(:))]; %#ok<AGROW>
                valid_count = valid_count + nnz(valid);
                active_count = active_count + nnz(active);
            end
            row_idx = row_idx + 1;
            rows(row_idx,:) = {scenario, level, manifest.levels.(level), ...
                numel(files), paired, rms(sync_values), rms(los_values), ...
                rms(shift_values), rms(phase_values), valid_count/active_count};
        end
    end
    summary = cell2table(rows, 'VariableNames', {'scenario', 'level', ...
        'multiplier', 'patch_count', 'paired_inputs_identical', ...
        'sync_rms_rad', 'los_rms_m', 'displacement_rms_px', ...
        'edge_phase_delta_rms_rad', 'valid_fraction'});
    writetable(summary, fullfile(sweep_root, 'phase4_sweep_summary.csv'));
    disp(summary);
    assert(all(summary.paired_inputs_identical), ...
        'dem2phase:UnpairedPhase4Sweep', ...
        'At least one sweep cell does not share identical paired inputs.');
end
