function summary = analyze_compound_failure_pilot()
%ANALYZE_COMPOUND_FAILURE_PILOT Export and verify compound-failure labels.
    script_dir = fileparts(mfilename('fullpath'));
    project_root = fileparts(script_dir);
    root = fullfile(project_root, 'data', 'phase4_sweep', ...
        'compound_failure_failure');
    files = dir(fullfile(root, 'patch_groups', '*.mat'));
    assert(~isempty(files), 'dem2phase:NoCompoundFailurePilot', ...
        'Generate the compound-failure pilot first.');
    rows = cell(numel(files), 10);
    for idx = 1:numel(files)
        data = load(fullfile(files(idx).folder, files(idx).name), ...
            'failure_labels', 'valid_edge_mask', 'metadata');
        labels = data.failure_labels;
        rows(idx,:) = {data.metadata.patch_name, ...
            sprintf('%d', data.valid_edge_mask), ...
            labels.dropout_present, labels.sync_anomaly_present, ...
            labels.low_coherence_fraction, labels.low_coherence_present, ...
            labels.shortest_baseline_active, labels.longest_baseline_active, ...
            labels.compound_failure_present, labels.failure_factor_count};
    end
    summary = cell2table(rows, 'VariableNames', {'patch_name', ...
        'valid_edge_mask', 'dropout_present', 'sync_anomaly_present', ...
        'low_coherence_fraction', 'low_coherence_present', ...
        'shortest_baseline_active', 'longest_baseline_active', ...
        'compound_failure_present', 'failure_factor_count'});
    writetable(summary, fullfile(root, 'compound_failure_summary.csv'));
    assert(all(summary.dropout_present) && all(summary.sync_anomaly_present) && ...
        all(summary.shortest_baseline_active) && ...
        all(summary.longest_baseline_active), ...
        'dem2phase:InvalidCompoundFailurePilot', ...
        'Required compound-failure factors are missing.');
    disp(summary);
end
