function export_cross_language_golden(output_path)
%EXPORT_CROSS_LANGUAGE_GOLDEN Export deterministic MATLAB reference arrays.
% Random residual amplitudes are zero. The fixture exercises fixed bicubic
% cropping, DEM-to-phase physics, terrain features, categorical sampling,
% convolution, and the Phase-4 linear registration convention.

    script_dir = fileparts(mfilename('fullpath'));
    project_root = fileparts(script_dir);
    addpath(genpath(project_root));
    if nargin < 1 || isempty(output_path)
        output_path = fullfile(project_root, 'python', 'tests', 'fixtures', ...
            'matlab_cross_language_golden.mat');
    end
    output_dir = fileparts(output_path);
    if ~exist(output_dir, 'dir'); mkdir(output_dir); end

    cfg = load_sim_config(fullfile(project_root, 'configs', ...
        'uav_p_500m_monostatic.json'));
    source_rows = 40;
    source_cols = 44;
    [source_x, source_y] = meshgrid(1:source_cols, 1:source_rows);
    source_dem = 120 + 0.7*source_x + 1.2*source_y + ...
        8*sin(source_x/6).*cos(source_y/7) + ...
        4*exp(-((source_x-27).^2 + (source_y-19).^2)/90);

    scale = 2.5;
    scaled_rows = round(scale*source_rows);
    scaled_cols = round(scale*source_cols);
    [base_x, base_y] = meshgrid(1:source_cols, 1:source_rows);
    [query_x, query_y] = meshgrid(linspace(1, source_cols, scaled_cols), ...
        linspace(1, source_rows, scaled_rows));
    scaled_dem = interp2(base_x, base_y, source_dem, query_x, query_y, 'bicubic');
    crop_bounds_1based = [17 23 48 58];
    dem_patch = scaled_dem(crop_bounds_1based(1):crop_bounds_1based(3), ...
        crop_bounds_1based(2):crop_bounds_1based(4));
    dem_patch = dem_patch - min(dem_patch(:));
    pixel_spacing_m = double(cfg.dataset.source_dem_pixel_spacing_m)/scale;

    class_codes = uint8([10 20 30 40 50 60 70 80 90 100]);
    source_landcover = class_codes(1 + mod(floor((source_x-1)/7) + ...
        floor((source_y-1)/6), numel(class_codes)));
    source_row_index = min(max(round(1 + ...
        ((crop_bounds_1based(1):crop_bounds_1based(3))-1) * ...
        (source_rows-1)/(scaled_rows-1)), 1), source_rows);
    source_col_index = min(max(round(1 + ...
        ((crop_bounds_1based(2):crop_bounds_1based(4))-1) * ...
        (source_cols-1)/(scaled_cols-1)), 1), source_cols);
    landcover_patch = source_landcover(source_row_index, source_col_index);

    baselines_m = double(cfg.interferometry.baseline_perp_m(:)');
    phase_ratios_rad_per_m = double(cfg.physics.dem2phase_ratios_rad_per_m(:)');
    ambiguity_heights_m = double(cfg.physics.ambiguity_heights_m(:)');
    unwrapped_phase = zeros(numel(baselines_m), size(dem_patch,1), size(dem_patch,2));
    wrapped_phase = zeros(size(unwrapped_phase));
    for edge_idx = 1:numel(baselines_m)
        phase = dem_patch * phase_ratios_rad_per_m(edge_idx);
        unwrapped_phase(edge_idx,:,:) = phase;
        wrapped_phase(edge_idx,:,:) = angle(exp(1i*phase));
    end

    [coherence_cell, terrain] = gen_coherence_map_multibaseline_terrainaware( ...
        dem_patch, baselines_m, ...
        'pixel_spacing_m', pixel_spacing_m, ...
        'incidence_angle_deg', double(cfg.geometry.incidence_angle_deg), ...
        'look_azimuth_deg', double(cfg.geometry.look_azimuth_deg), ...
        'min_coh', double(cfg.coherence.min), ...
        'max_coh', double(cfg.coherence.max), ...
        'baseline_decay_model', char(cfg.coherence.baseline_decay_model), ...
        'critical_baseline_m', double(cfg.physics.critical_baseline_m), ...
        'terrain_normalization_model', char(cfg.coherence.terrain_normalization_model), ...
        'slope_scale_deg', double(cfg.coherence.slope_scale_deg), ...
        'roughness_scale_m', double(cfg.coherence.roughness_scale_m), ...
        'curvature_scale_per_m', double(cfg.coherence.curvature_scale_per_m), ...
        'slope_weight', double(cfg.coherence.slope_weight), ...
        'roughness_weight', double(cfg.coherence.roughness_weight), ...
        'curvature_weight', double(cfg.coherence.curvature_weight), ...
        'shared_residual_std', 0, 'edge_residual_std', 0, ...
        'residual_scale_px', double(cfg.coherence.residual_scale_px), 'seed', 1);
    coherence_deterministic = cat(3, coherence_cell{:});
    coherence_deterministic = permute(coherence_deterministic, [3 1 2]);

    convolution_input = source_dem(5:20, 7:25);
    convolution_kernel = reshape(1:35, 5, 7);
    convolution_kernel = convolution_kernel/sum(convolution_kernel(:));
    convolution_same = conv2(convolution_input, convolution_kernel, 'same');

    [warp_x, warp_y] = meshgrid(1:size(dem_patch,2), 1:size(dem_patch,1));
    base_complex = (1 + 0.001*warp_x.*warp_y) .* ...
        exp(1i*(0.07*warp_x + 0.11*warp_y));
    row_axis = linspace(-0.5, 0.5, size(dem_patch,1))';
    range_displacement_px = 0.35 + 0.12*row_axis;
    azimuth_displacement_px = -0.40 + 0.08*row_axis;
    registration_query_x = warp_x - repmat(range_displacement_px, 1, size(warp_x,2));
    registration_query_y = warp_y - repmat(azimuth_displacement_px, 1, size(warp_y,2));
    registered_complex = interp2(warp_x, warp_y, real(base_complex), ...
        registration_query_x, registration_query_y, 'linear', 0) + ...
        1i*interp2(warp_x, warp_y, imag(base_complex), ...
        registration_query_x, registration_query_y, 'linear', 0);
    registration_valid_mask = registration_query_x >= 1 & ...
        registration_query_x <= size(warp_x,2) & registration_query_y >= 1 & ...
        registration_query_y <= size(warp_y,1);

    wavelength_m = double(cfg.physics.wavelength_m);
    critical_baseline_m = double(cfg.physics.critical_baseline_m);
    range_resolution_m = double(cfg.physics.range_resolution_m);
    fixture_schema_version = uint16(1);
    save(output_path, 'fixture_schema_version', 'source_dem', 'scale', ...
        'scaled_rows', 'scaled_cols', 'crop_bounds_1based', 'dem_patch', ...
        'pixel_spacing_m', 'source_landcover', 'source_row_index', ...
        'source_col_index', 'landcover_patch', 'baselines_m', ...
        'phase_ratios_rad_per_m', 'ambiguity_heights_m', 'wavelength_m', ...
        'critical_baseline_m', 'range_resolution_m', 'unwrapped_phase', ...
        'wrapped_phase', 'terrain', 'coherence_deterministic', ...
        'convolution_input', 'convolution_kernel', 'convolution_same', ...
        'base_complex', 'range_displacement_px', 'azimuth_displacement_px', ...
        'registered_complex', 'registration_valid_mask', '-v7');
    fprintf('Golden fixture written: %s\n', output_path);
end
